version: "3.9"
services:
  db:
    image: postgres:15
    container_name: silentmanager-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: silent
      POSTGRES_PASSWORD: silent
      POSTGRES_DB: silentmanager
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
